post_onboarding:  {
  completed_steps:  POST_ONBOARDING_STEP_TYPE_MANAGER_WELCOME
  completed_steps:  POST_ONBOARDING_STEP_TYPE_USAGE_MODE
  completed_steps:  POST_ONBOARDING_STEP_TYPE_AGENT_CONFIGURATION
  completed_steps:  POST_ONBOARDING_STEP_TYPE_ADD_WORKSPACE
}
seen_nuxs:  {
  uids:  31
  uids:  29
  uids:  24
}
agent_onboarding_completed:  AGENT_ONBOARDING_STATE_COMPLETED
last_selected_agent_model:  MODEL_PLACEHOLDER_M16
migrate_convos_into_projects:  MIGRATION_STATUS_COMPLETED
installation_uuid:  "ecc7bcc1-f551-46bf-b848-c186cd590ccd"
migrate_retroactive_projects:  RETROACTIVE_MIGRATION_STATUS_COMPLETED_UNNECESSARY
migrations:  {
  key:  2
  value:  MIGRATION_STATUS_COMPLETED
}
migrations:  {
  key:  3
  value:  MIGRATION_STATUS_COMPLETED
}
